import { Router } from 'express';
import { getCourses,getCourseById,createNewCourse,updateCourse,deleteCourse } from '../controllers/course.controllers.js';
import {validate} from '../middlewares/validate.middlewares.js';
import {createCourseValidator} from '../validators/courses.validators.js';
import { authenticateToken } from '../middlewares/auth.middlewares.js';
const router = Router();
router.get('/', getCourses);
router.get('/:id', getCourseById);
router.post("/",authenticateToken,createCourseValidator, validate, createNewCourse);
router.put('/:id', authenticateToken,createCourseValidator, validate, updateCourse);
router.delete('/:id',authenticateToken,deleteCourse);
export default router;